# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92a60a7da09d92057bc7690a9137cabdee3cdc668587a8ecff9dacf244beb146e6ebbc5f94e59551ebeccaaffc9d1e8b875227f8801c318cf6eaf9d284e5d5e9

test:
  secret_key_base: bfe2ce8059333ff0fe0004ae83048c2e14124301a9866714a0fe257e9e864a970ffdda1bf4f39e94c38a301393c42c64dd4de58fb413162576fe11b1a6a3984f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
